import pandas as pd


# ============================================================
# 1. Load cleaned dataset
# ============================================================

INPUT_FILE = r"C:\Users\likit\OneDrive\Documents\Customer-Cohort-Retention-Analysis\data\cleaned_retail_data.csv"
print("Loading cleaned dataset...")

df = pd.read_csv(
    INPUT_FILE,
    parse_dates=["InvoiceDate"]
)

print("Dataset loaded successfully!")


# ============================================================
# 2. Determine Analysis Date
# ============================================================

# We use one day after the last transaction as the
# reference date for calculating customer recency.

analysis_date = (
    df["InvoiceDate"].max()
    + pd.Timedelta(days=1)
)

print("\nAnalysis Date:")
print(analysis_date)


# ============================================================
# 3. Create Customer-Level Metrics
# ============================================================

customer_metrics = (
    df.groupby("CustomerID")
      .agg(
          FirstPurchase=("InvoiceDate", "min"),
          LastPurchase=("InvoiceDate", "max"),
          Orders=("InvoiceNo", "nunique"),
          Revenue=("Revenue", "sum"),
          Quantity=("Quantity", "sum")
      )
      .reset_index()
)


# ============================================================
# 4. Calculate Recency
# ============================================================

# Recency = number of days since customer's last purchase

customer_metrics["Recency"] = (
    analysis_date
    - customer_metrics["LastPurchase"]
).dt.days


# ============================================================
# 5. Calculate Frequency
# ============================================================

# Frequency = number of unique orders

customer_metrics["Frequency"] = (
    customer_metrics["Orders"]
)


# ============================================================
# 6. Calculate Monetary Value
# ============================================================

# Monetary = total revenue generated by customer

customer_metrics["Monetary"] = (
    customer_metrics["Revenue"]
)


# ============================================================
# 7. Customer Retention Status
# ============================================================

def retention_status(recency):

    if recency <= 30:
        return "Active"

    elif recency <= 90:
        return "At Risk"

    else:
        return "Churned"


customer_metrics["Status"] = (
    customer_metrics["Recency"]
    .apply(retention_status)
)


# ============================================================
# 8. Customer Lifetime Value
# ============================================================

# Historical CLV = total revenue generated
# by the customer during the available period.

customer_metrics["Customer_Lifetime_Value"] = (
    customer_metrics["Revenue"]
)


# ============================================================
# 9. Display Customer Metrics
# ============================================================

print("\n==========================================")
print("        CUSTOMER METRICS")
print("==========================================")

print(
    customer_metrics.head(20)
)


# ============================================================
# 10. Customer Statistics
# ============================================================

print("\n==========================================")
print("        CUSTOMER STATISTICS")
print("==========================================")

print(
    "\nAverage Recency:",
    round(customer_metrics["Recency"].mean(), 2),
    "days"
)

print(
    "Average Frequency:",
    round(customer_metrics["Frequency"].mean(), 2),
    "orders"
)

print(
    "Average Monetary Value: £",
    round(customer_metrics["Monetary"].mean(), 2)
)


# ============================================================
# 11. Customer Status Analysis
# ============================================================

status_counts = (
    customer_metrics["Status"]
    .value_counts()
)


print("\n==========================================")
print("        CUSTOMER STATUS")
print("==========================================")

print(status_counts)


# ============================================================
# 12. Revenue by Customer Status
# ============================================================

status_revenue = (
    customer_metrics
    .groupby("Status")["Revenue"]
    .sum()
    .sort_values(
        ascending=False
    )
)


print("\n==========================================")
print("       REVENUE BY CUSTOMER STATUS")
print("==========================================")

print(status_revenue)


# ============================================================
# 13. Save Customer Metrics
# ============================================================

OUTPUT_FILE = (
    "output/customer_metrics.csv"
)

customer_metrics.to_csv(
    OUTPUT_FILE,
    index=False
)


print("\n==========================================")
print("     CUSTOMER METRICS SAVED")
print("==========================================")

print(
    f"File saved to: {OUTPUT_FILE}"
)